// Autogenerated from Pigeon (v9.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif



private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

enum QuestionType: Int {
  case singleChoice = 0
}

/// Generated class from Pigeon that represents data sent in messages.
struct QuizModel {
  var questions: [QuestionModel?]
  var startImageUrl: String? = nil
  var endImageUrl: String? = nil
  var startTitle: String? = nil
  var startDescription: String? = nil
  var endTitle: String? = nil
  var endDescription: String? = nil
  var nextButtonTitle: String
  var seedColor: String? = nil

  static func fromList(_ list: [Any?]) -> QuizModel? {
    let questions = list[0] as! [QuestionModel?]
    let startImageUrl = list[1] as? String
    let endImageUrl = list[2] as? String
    let startTitle = list[3] as? String
    let startDescription = list[4] as? String
    let endTitle = list[5] as? String
    let endDescription = list[6] as? String
    let nextButtonTitle = list[7] as! String
    let seedColor = list[8] as? String

    return QuizModel(
      questions: questions,
      startImageUrl: startImageUrl,
      endImageUrl: endImageUrl,
      startTitle: startTitle,
      startDescription: startDescription,
      endTitle: endTitle,
      endDescription: endDescription,
      nextButtonTitle: nextButtonTitle,
      seedColor: seedColor
    )
  }
  func toList() -> [Any?] {
    return [
      questions,
      startImageUrl,
      endImageUrl,
      startTitle,
      startDescription,
      endTitle,
      endDescription,
      nextButtonTitle,
      seedColor,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QuestionModel {
  var id: String
  var type: QuestionType
  var image: String? = nil
  var title: String
  var description: String? = nil
  var options: [Option?]

  static func fromList(_ list: [Any?]) -> QuestionModel? {
    let id = list[0] as! String
    let type = QuestionType(rawValue: list[1] as! Int)!
    let image = list[2] as? String
    let title = list[3] as! String
    let description = list[4] as? String
    let options = list[5] as! [Option?]

    return QuestionModel(
      id: id,
      type: type,
      image: image,
      title: title,
      description: description,
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type.rawValue,
      image,
      title,
      description,
      options,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Option {
  var id: String
  var text: String

  static func fromList(_ list: [Any?]) -> Option? {
    let id = list[0] as! String
    let text = list[1] as! String

    return Option(
      id: id,
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      text,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnswerModel {
  var questionId: String
  var optionId: String? = nil
  var text: String? = nil

  static func fromList(_ list: [Any?]) -> AnswerModel? {
    let questionId = list[0] as! String
    let optionId = list[1] as? String
    let text = list[2] as? String

    return AnswerModel(
      questionId: questionId,
      optionId: optionId,
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      questionId,
      optionId,
      text,
    ]
  }
}
private class QuizApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return AnswerModel.fromList(self.readValue() as! [Any])
      case 129:
        return Option.fromList(self.readValue() as! [Any])
      case 130:
        return QuestionModel.fromList(self.readValue() as! [Any])
      case 131:
        return QuizModel.fromList(self.readValue() as! [Any])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class QuizApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AnswerModel {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? Option {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? QuestionModel {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? QuizModel {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class QuizApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return QuizApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return QuizApiCodecWriter(data: data)
  }
}

class QuizApiCodec: FlutterStandardMessageCodec {
  static let shared = QuizApiCodec(readerWriter: QuizApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol QuizApi {
  func getQuiz() throws -> QuizModel
  func sendAnswers(answers: [AnswerModel]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class QuizApiSetup {
  /// The codec used by QuizApi.
  static var codec: FlutterStandardMessageCodec { QuizApiCodec.shared }
  /// Sets up an instance of `QuizApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: QuizApi?) {
    let getQuizChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.QuizApi.getQuiz", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getQuizChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getQuiz()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getQuizChannel.setMessageHandler(nil)
    }
    let sendAnswersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.QuizApi.sendAnswers", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendAnswersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let answersArg = args[0] as! [AnswerModel]
        do {
          try api.sendAnswers(answers: answersArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendAnswersChannel.setMessageHandler(nil)
    }
  }
}
